version: "2"
  
services:
  otp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: quay.io/cloudian/cqc:dev
    hostname: otp000
    privileged: true
    dns:
      - 127.0.0.1
      - 8.8.8.8
    dns_search:
      - localdomain
    volumes:
      - ~/.ssh:/home/worker/.ssh
